### ISSUE TITLE
🐛 [Bug report]: An issue with Create Testimonial

### ISSUE THREAD

**Issue by Shivam-Katare** [reactplay/react-play#1520]
### Descrcibe the bug?

When we try to create a testimonial and click on the Create Testimonial button, the page refreshes, adding a refreshToken to the URL. Each time this happens, a new refreshToken is added, and the page refreshes again, but nothing else happens.

`
https://reactplay.io/testimonials?refreshToken=5eb18423-2820-4c87-85aa-d164ceee5b64?refreshToken=1b333bf2-f259-494b-bf9d-ae52e6bad6f2?refreshToken=e5616046-17b0-433a-ad9f-cc1af85647a0?refreshToken=e059bea3-8b2b-4825-801f-4410575d72e4
`

### Steps to reproduce the bug?

1. Go to the ReactPlay site
2. Scroll down to the `Testimonial` Section
3. Click on the `View All Testimonial`
4. Now, click on the `Create Testimonial` Button
5. It will now first ask for authorization if you're already authorized with Github, it refreshes the page and adds a `refreshToken` to the URL but nothing else happens.

### Expected behavior

When the "Create Testimonial" button is clicked, a text box or modal should open where the user can share their feedback or experience. After saving, the new testimonial should be added to the list and displayed alongside others.

### Desktop (Please provide your system information)

OS: Windows
Browser: Chrome

### Record

- [X] I have checked the existing [issues](https://github.com/reactplay/react-play/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/reactplay/react-play/blob/main/CONTRIBUTING.md)
- [ ] I want to work on this issue
- [ ] I am a Hacktoberfest contributor

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by priyankarpal** [comment]
> I want to work on this , please assign me this

sure assigned to you

**Comment by priyankarpal** [comment]
@Goutamchoudhary907 Can you update me on the progress of this particular issue?

**Comment by priyankarpal** [comment]
> Just started working on it now ,I had my exams so couldn't work till now

ok ok

**Comment by PriteshKiri** [comment]
Hey @Goutamchoudhary907,

I hope you're doing well! 

Just wanted to check in and see if you’re facing any challenges with this issue. It’s been over two weeks since it was assigned, and we’d appreciate it if you could wrap it up in the next three days. If not, we might need to reassign it. 

Thanks for your understanding! Looking forward to your contribution.

**Comment by Goutamchoudhary907** [comment]
Hey @PriteshKiri @priyankarpal I try to solve the bug but i found that the all files of testimonial is well structured and there is no bug , i add some console logs and try to find the error then i remove all my updates and see that i am able to addtestimonials there is no issue when i run the site locally . Now i dont understand why it is not working from your side , see below screenshoots 
![Screenshot 2024-10-14 200735](https://github.com/user-attachments/assets/c511b194-c891-48f9-8e20-513453f975a5)

**Comment by Goutamchoudhary907** [comment]
Hey @PriteshKiri  @priyankarpal  i check all the files related files to testmonial and didn't find any error then i add some console logs to check errors , after that i undo all my changes and then check site in my local host it is working properly i able to add testimonial , i dont know how this is possible i just add this dependency to the package.json file ( "@babel/plugin-proposal-private-property-in-object": "^7.21.11",
)
but i dont think it is running because of this 
![Screenshot 2024-10-14 200735](https://github.com/user-attachments/assets/65bc558e-0cae-4a1c-bec6-494ad2de7c98)

**Comment by PriteshKiri** [comment]
@Shivam-Katare can you please look into this?

**Comment by Shivam-Katare** [comment]
I checked that @PriteshKiri, and it's not working. It's just adding a `refreshToken` into the url. I think the issue is with authorization that's why this issue is also happening #1540
