### ISSUE TITLE
🐛 [Bug report]: Can't setup development mode

### ISSUE THREAD

**Issue by nova9** [reactplay/react-play#330]
**Describe the bug**
Can't setup ReactPlay for development

**To Reproduce**
1. Follow  "How to Set up ReactPlay for Development?" guide at [the official repository](https://github.com/reactplay/react-play/blob/main/README.md)

**Expected behavior**
"npm i" fails

**Screenshots**
<img width="777" alt="Screenshot 2022-06-20 at 16 49 20" src="https://user-images.githubusercontent.com/27461049/174592235-926c8d0f-89e4-41de-a6d0-6e6ee843b1dc.png">

**Desktop (please complete the following information):**
 - OS: [macOS]

**Additional context**
Method of adding plays is not scalable. How many dependancies does a person need to install just to add a play. So many dependancies. So many conflicts. At some point developers will have to download a huge repository and install a huge amount of dependancies just to get started.

**Comment by atapas** [comment]
Hey @nova9

I think it is because React play is on v18 but the shimmer library is still not compatible yet. Please let us know if `npm i --legacy-peer-deps` fixes it for you.

I agree with your concern about bloating a single repo with many plays. We are already working on it to make it lightweight and separate them out. You can check more about it from here: https://github.com/reactplay/react-play/issues/328

Thanks!

**Comment by atapas** [comment]
Hi @nova9 Did you get a chance to try it out?

**Comment by nova9** [comment]
I just did. "--legact-peer-deps" Work. Sometimes I had to run it twice but it worked.
