### ISSUE TITLE
🐛 [Bug report]: Filter modal checkbox bug

### ISSUE THREAD

**Issue by Angryman18** [reactplay/react-play#876]
### Descrcibe the bug?

in the filter modal at select language section there is a bug. when you select all (both javascript and typescript) at language selectbox and after that you try to uncheck a single language then it unchecks the oposite one. lets say you have both javascript and typescript checkbox selected and now you want to uncheck typescript so upon clicking on typescript it unchecks javascript which should not happen. 

### Steps to reproduce the bug?

already described above

### Expected behavior

it should uncheck that one which user clicks not the opposite one

### Desktop (Please provide your system information)

--

### Mobile (Please provide your device information)

--

### Screenshot / Screenshare

![Screenshot from 2023-01-14 19-49-46](https://user-images.githubusercontent.com/63530626/212476717-9c039220-bab0-4838-a2f1-415022aafcef.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Angryman18** [comment]
@supminn can you look into this.

**Comment by supminn** [comment]
Hi @Angryman18 
The functionality is that way. For any of the filters, if we selected all, and then click on a particular item, it would update the filter and select just that item.

This might be a bit confusing in the case of language since we have only 2 options available. Nevertheless, this functionality is consistent among all the filters.

**Comment by Angryman18** [comment]
oh okay its fine then. closing the issue. :)
