### ISSUE TITLE
🐛 [Bug report]: Broken Github link for plays

### ISSUE THREAD

**Issue by shrilakshmishastry** [reactplay/react-play#995]
### Descrcibe the bug?

some links to github code is broken for some plays.eg. [play](https://reactplay.io/plays/shivam-katare/tube2tunes) . Upon clicking source code link for play it shows 404 error

### Steps to reproduce the bug?

1. GO to react play 
2. got to https://reactplay.io/plays/shivam-katare/tube2tunes
3. click on github icon which takes to source code of play

### Expected behavior

It should show proper code base

### Desktop (Please provide your system information)

Browser firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by atapas** [comment]
Thanks for finding it.

@koustov i suspect the plays that were created with space or special char in name? Can you please check?

**Comment by Shivam-Katare** [comment]
Hey @tapas, I have checked the issue. The github link shows the 404 error because of the name of the plays. Plays having Capital letters or numbers in between the words without having space face this problem. 

### Example: 

- Tube**2**Tunes
- Photoshop**A**pp
- code**N**chill
- Image Gallary using un**S**plash API
- Multi**S**elect Component

And, this problem is only faced by the plays that are created after October 2022.
So, either we have to fix the name of each play(which will not be an optimal solution) or have to fix it from the backend side.

**Comment by priyankarpal** [comment]
Can you update me on the progress of this particular issue?
